language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

before_install:
  - gem --version
  - stty cols 80

script:
  - bundle exec rake spec

#branches:
#  only:
#  - master

matrix:
  allow_failures:
    - rvm: ruby-head